name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.2.0
    - name: Build with Gradle
      run: ./gradlew build
    - name: Kotlin Linter
      uses: vroy/gha-kotlin-linter@v4
